[(InsideFunctionCall((RuntimeError(BreakOutsideLoop), (16, 22))), (25, 31)), (RuntimeError(ReturnOutsideFunction), (33, 42))]
