[(RuntimeError(ContinueOutsideLoop), (6, 15))]
